[variables]
PYTHONPATH = "/app"

providers = ["python"]

[phases.build]
cmds = ["pip install Flask flask-limiter google-genai gunicorn werkzeug"]

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app"